# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'contact_window_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(516, 208)
        self.label_name = QtWidgets.QLabel(Dialog)
        self.label_name.setGeometry(QtCore.QRect(30, 40, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_name.setFont(font)
        self.label_name.setObjectName("label")
        self.label_surname = QtWidgets.QLabel(Dialog)
        self.label_surname.setGeometry(QtCore.QRect(30, 90, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_surname.setFont(font)
        self.label_surname.setObjectName("label_2")
        self.label_number = QtWidgets.QLabel(Dialog)
        self.label_number.setGeometry(QtCore.QRect(270, 40, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_number.setFont(font)
        self.label_number.setObjectName("label_3")
        self.label_mail = QtWidgets.QLabel(Dialog)
        self.label_mail.setGeometry(QtCore.QRect(270, 90, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_mail.setFont(font)
        self.label_mail.setObjectName("label_4")
        self.pushButton_refactor = QtWidgets.QPushButton(Dialog)
        self.pushButton_refactor.setGeometry(QtCore.QRect(340, 170, 101, 28))
        self.pushButton_refactor.setObjectName("pushButton")
        self.label_description = QtWidgets.QLabel(Dialog)
        self.label_description.setGeometry(QtCore.QRect(30, 130, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_description.setFont(font)
        self.label_description.setObjectName("label_5")
        self.lineEdit_name = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_name.setEnabled(False)
        self.lineEdit_name.setGeometry(QtCore.QRect(80, 40, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_name.setFont(font)
        self.lineEdit_name.setObjectName("lineEdit")
        self.lineEdit_description = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_description.setEnabled(False)
        self.lineEdit_description.setGeometry(QtCore.QRect(30, 150, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_description.setFont(font)
        self.lineEdit_description.setText("")
        self.lineEdit_description.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_description.setObjectName("lineEdit_5")
        self.lineEdit_surname = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_surname.setEnabled(False)
        self.lineEdit_surname.setGeometry(QtCore.QRect(120, 90, 113, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_surname.setFont(font)
        self.lineEdit_surname.setObjectName("lineEdit_2")
        self.lineEdit_number = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_number.setEnabled(False)
        self.lineEdit_number.setGeometry(QtCore.QRect(340, 40, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_number.setFont(font)
        self.lineEdit_number.setText("")
        self.lineEdit_number.setObjectName("lineEdit_3")
        self.lineEdit_mail = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_mail.setEnabled(False)
        self.lineEdit_mail.setGeometry(QtCore.QRect(340, 90, 131, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_mail.setFont(font)
        self.lineEdit_mail.setObjectName("lineEdit_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Контакт"))
        self.label_name.setText(_translate("Dialog", "Имя:"))
        self.label_surname.setText(_translate("Dialog", "Фамилия:"))
        self.label_number.setText(_translate("Dialog", "Номер:"))
        self.label_mail.setText(_translate("Dialog", "Почта:"))
        self.pushButton_refactor.setText(_translate("Dialog", "Редактировать"))
        self.label_description.setText(_translate("Dialog", "Описание:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
