# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delete_window_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(392, 245)
        Dialog.setMinimumSize(QtCore.QSize(392, 245))
        Dialog.setMaximumSize(QtCore.QSize(392, 245))
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(80, 50, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_delete_contact = QtWidgets.QPushButton(Dialog)
        self.pushButton_delete_contact.setGeometry(QtCore.QRect(90, 190, 93, 28))
        self.pushButton_delete_contact.setObjectName("pushButton")
        self.pushButton_cancel_delete = QtWidgets.QPushButton(Dialog)
        self.pushButton_cancel_delete.setGeometry(QtCore.QRect(220, 190, 93, 28))
        self.pushButton_cancel_delete.setObjectName("pushButton_2")
        self.lineEdit_id = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_id.setGeometry(QtCore.QRect(150, 120, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_id.setFont(font)
        self.lineEdit_id.setText("")
        self.lineEdit_id.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(140, 80, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Удалить контакт"))
        self.label.setText(_translate("Dialog", "Введите ID контакта, который"))
        self.pushButton_delete_contact.setText(_translate("Dialog", "Удалить"))
        self.pushButton_cancel_delete.setText(_translate("Dialog", "Отмена"))
        self.label_2.setText(_translate("Dialog", "хотите удалить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
