# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_window_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(553, 250)
        self.pushButton_add_contact = QtWidgets.QPushButton(Dialog)
        self.pushButton_add_contact.setGeometry(QtCore.QRect(320, 210, 93, 28))
        self.pushButton_add_contact.setObjectName("pushButton")
        self.pushButton_cancel_add = QtWidgets.QPushButton(Dialog)
        self.pushButton_cancel_add.setGeometry(QtCore.QRect(420, 210, 93, 28))
        self.pushButton_cancel_add.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 30, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 130, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 190, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_name_add = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_name_add.setGeometry(QtCore.QRect(140, 30, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_name_add.setFont(font)
        self.lineEdit_name_add.setText("")
        self.lineEdit_name_add.setObjectName("lineEdit")
        self.lineEdit_surname_add = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_surname_add.setGeometry(QtCore.QRect(90, 80, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_surname_add.setFont(font)
        self.lineEdit_surname_add.setText("")
        self.lineEdit_surname_add.setObjectName("lineEdit_2")
        self.lineEdit_mail_add = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_mail_add.setGeometry(QtCore.QRect(110, 180, 191, 31))
        self.lineEdit_mail_add.setText("")
        self.lineEdit_mail_add.setObjectName("lineEdit_3")
        self.lineEdit_mail_add = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_mail_add.setGeometry(QtCore.QRect(110, 130, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_mail_add.setFont(font)
        self.lineEdit_mail_add.setText("")
        self.lineEdit_mail_add.setObjectName("lineEdit_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Добавить контакт"))
        self.pushButton_add_contact.setText(_translate("Dialog", "Добавить"))
        self.pushButton_cancel_add.setText(_translate("Dialog", "Отмена"))
        self.label.setText(_translate("Dialog", "Фамилия:"))
        self.label_2.setText(_translate("Dialog", "Имя:"))
        self.label_3.setText(_translate("Dialog", "Номер:"))
        self.label_4.setText(_translate("Dialog", "Почта:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
